name: Build
on:
  workflow_dispatch:
  pull_request:
  push:
    branches: [main]
permissions:
  contents: read
jobs:
  build-package:
    name: Build Package
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout Project
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Setup Node.js
        uses: actions/setup-node@39370e3970a6d050c480ffad4ff0ed4d3fdee5af # v4.1.0
        with:
          node-version-file: .nvmrc

      - name: Setup Yarn
        uses: threeal/setup-yarn-action@ec8c075e62bc497968de40011c2b766f5e8f1ac5 # v2.0.0

      - name: Build Package
        run: yarn build

      - name: Check Diff
        run: git diff && git diff-index --quiet --exit-code HEAD
